<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="AKSHAY" failures="1" tests="4" name="Test" time="20.034" errors="0" timestamp="2023-07-16T14:32:02 IST">
  <testcase classname="ltim.practise2.TestApp" name="isSiteLoaded" time="0.09"/>
  <testcase classname="ltim.practise2.TestApp" name="searchProcuct" time="9.214"/>
  <testcase classname="ltim.practise2.TestApp" name="listOfIhones" time="9.999"/>
  <testcase classname="ltim.practise2.TestApp" name="isInStock" time="0.335">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at ltim.practise2.TestApp.isInStock(TestApp.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- isInStock -->
  <testcase classname="ltim.practise2.BaseTest" name="@BeforeSuite launchURL" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite launchURL -->
  <testcase classname="ltim.practise2.BaseTest" name="@AfterSuite afterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
</testsuite> <!-- Test -->
